theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: Java开发

# 对你自己的简洁描述
description: 熟练掌握了redisson分布式锁、aqs并发锁、MySQL优化、Java性能优化、GC内存模型和GC算法，数据结构、Java技术栈等。

# 你的美照地址
logo: /assets/images/me.jpg

# 你的名字
name: 司磊

# 你的联系方式
phone: 18767160845

# 你的邮箱
email: 523612251@qq.com

# 你目前的住址
address: 浙江省杭州市拱墅区方家花园21栋一单元1303

# 你毕业院校
school: 杭州电子科技大学

# 你的专业
profession: 软件技术

# 你的学位
degree: 学士

# 你获得过的证书或奖励
credential: 三届MVP/三届NBA冠军
